services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=urlshortener'
      - 'MONGO_INITDB_ROOT_PASSWORD=root'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    hostname: mongodb
    ports:
      - '27017'
  redis:
    image: 'redis:latest'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
    hostname: redis
    ports:
      - '6379'
